[metadata]
name = ecmc-ioc-generator
version = 1.0.0
description = EtherCAT bus scanner and ecmc IOC generator
author = Markus Kristensson
author_email = markus.kristensson@ess.eu

[options]
py_modules = ecmc_ioc_gen
python_requires = >=2.7
install_requires =

[options.entry_points]
console_scripts =
    ecmc-ioc-gen = ecmc_ioc_gen:main
